spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # un jour
      refresh-token:
        expiration: 604800000 # 7 jours

security:
  oauth2:
    client:
      registration:
        github:
          clientId: github-client-id
          clientSecret: github-client-secret
